name: Flake8 CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11, 3.12]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install flake8-docstrings
    - name: Set Environments
      run: |
        echo SECRET_KEY=${{ secrets.SECRET_KEY }} > .env
        echo DEBUG=${{ secrets.DEBUG }} >> .env
        echo TIME_ZONE=${{ secrets.TIME_ZONE }} >> .env
        echo ALLOWED_HOSTS=${{ secrets.ALLOWED_HOSTS }} >> .env
        echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env

    - name: Run flake8
      run: |
        # Run flake8 on specific files
        flake8 polls/admin.py polls/apps.py polls/models.py polls/urls.py polls/views.py
        
        # Run flake8 on all Python files in polls/tests directory except __init__.py
        find polls/tests/ -name "*.py" ! -name "__init__.py" -exec flake8 {} +
